name = "script"
compatibility_date = "2025-02-01"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = ".vercel/output/static"

[vars]
AI_PROVIDER = "mock"
D1_BINDING = "DB"
NEXT_PUBLIC_EDITOR_DEBUG = "true"

[[d1_databases]]
binding = "DB"
database_name = "script-staging"
database_id = "d8526a53-8fda-40f7-b330-e23f6d4c3858"
